language: node_js
node_js:
  - 13

services: 
  - docker

script:
  - docker --version
  - docker build -t udagram-reverseproxy ./udagram-reverseproxy
  - docker build -t udagram-api-feed ./udagram-api-feed
  - docker build -t udagram-api-user ./udagram-api-user
  - docker build -t udagram-frontend ./udagram-frontend

  - docker tag udagram-reverseproxy hopnh/udagram-reverseproxy:v2
  - docker tag udagram-api-feed hopnh/udagram-api-feed:v2
  - docker tag udagram-api-user hopnh/udagram-api-user:v2
  - docker tag udagram-frontend hopnh/udagram-frontend:v2

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push hopnh/udagram-reverseproxy:v2
  - docker push hopnh/udagram-api-feed:v2
  - docker push hopnh/udagram-api-user:v2
  - docker push hopnh/udagram-frontend:v2